# Generated by Django 5.0.3 on 2024-03-11 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('albumid', models.AutoField(primary_key=True, serialize=False)),
                ('albumname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('userpssword', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('albumid', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('videolink', models.CharField(max_length=100)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inStoryBackend.user')),
            ],
        ),
        migrations.CreateModel(
            name='FriendsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_a', to='inStoryBackend.user')),
                ('person_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_b', to='inStoryBackend.user')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inStoryBackend.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inStoryBackend.user')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='albumcreatorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inStoryBackend.user'),
        ),
    ]
