# Generated by Django 5.0.3 on 2024-03-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inStoryBackend', '0003_alter_album_albumcreatorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='participants',
            field=models.ManyToManyField(related_name='albums', through='inStoryBackend.AlbumList', to='inStoryBackend.user'),
        ),
    ]
